version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    networks:
      - internal
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    restart: always
    depends_on:
      - peppermint_postgres
    networks:
      - internal
    ports:
      - 1000:3000
      - 1001:5003
# If running via Docker on a hypervisor, enable DNS.
#    dns:
#      - 1.1.1.1
#      - 8.8.8.8
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "12345"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'

volumes:
  pgdata_live:

networks:
  internal:
